name: OpenShare
description: OpenShare - Cross platform app for sharing
homepage: https://openshare.app
documentation: https://openshare.app/docs
repository: https://github.com/OpenShareApp/OpenShare
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.9.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^3.1.0
  freezed_annotation: ^0.12.0
  meta: 1.1.8
  dartz: ^0.9.1
  connectivity: ^0.4.9+3
  equatable: ^1.2.5
  injectable: ^1.0.4
  path_provider: ^1.6.18
  mockito: ^4.1.0
  hive: ^1.4.4

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: 
  freezed: ^0.12.1
  json_serializable: ^3.5.0
  injectable_generator: ^1.0.4

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
